export const IS_OPEN_WINDOW_TOGGLE = 'IS_OPEN_WINDOW_TOGGLE';

export const PHARM_INIT_GET_REQUEST = 'PHARM_INIT_GET_REQUEST';
export const PHARM_INIT_GET_SUCCESS = 'PHARM_INIT_GET_SUCCESS';
export const PHARM_INIT_GET_FAILURE = 'PHARM_INIT_GET_FAILURE';

export const PHARM_GET_REQUEST = 'PHARM_GET_REQUEST';
export const PHARM_GET_SUCCESS = 'PHARM_GET_SUCCESS';
export const PHARM_GET_FAILURE = 'PHARM_GET_FAILURE';

export const PHARM_CREATE_REQUEST = 'PHARM_CREATE_REQUEST';
export const PHARM_CREATE_SUCCESS = 'PHARM_CREATE_SUCCESS';
export const PHARM_CREATE_FAILURE = 'PHARM_CREATE_FAILURE';

export const PHARM_EDIT_REQUEST = 'PHARM_EDIT_REQUEST';
export const PHARM_EDIT_SUCCESS = 'PHARM_EDIT_SUCCESS';
export const PHARM_EDIT_FAILURE = 'PHARM_EDIT_FAILURE';

export const PHARM_DELETE_REQUEST = 'PHARM_DELETE_REQUEST';
export const PHARM_DELETE_SUCCESS = 'PHARM_DELETE_SUCCESS';
export const PHARM_DELETE_FAILURE = 'PHARM_DELETE_FAILURE';
